services:
  truecode.api:
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TrueCode2024@
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    #volumes:
    #  - mssql-data:/var/opt/mssql

#volumes:
#  mssql-data: