// <auto-generated />
using System;
using Commands.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commands.Infrastructure.Migrations
{
    [DbContext(typeof(SQLContext))]
    [Migration("20241012023300_AddProductImageTable")]
    partial class AddProductImageTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commands.Infrastructure.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceWithDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49f8f7b6-1c72-8327-8565-01927e927391"),
                            Article = "1",
                            Condition = 1,
                            Description = "Product 1",
                            Name = "Product 1",
                            Price = 10.99m,
                            PriceWithDiscount = 8m
                        },
                        new
                        {
                            Id = new Guid("0e3952ee-c3a2-80c6-8566-01927e927391"),
                            Article = "2",
                            Condition = 1,
                            Description = "Product 2",
                            Name = "Product 2",
                            Price = 10.99m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("f01920c6-083c-884a-8567-01927e927391"),
                            Article = "3",
                            Condition = 1,
                            Description = "Product 3",
                            Name = "Product 3",
                            Price = 20m,
                            PriceWithDiscount = 11m
                        },
                        new
                        {
                            Id = new Guid("13bef071-fe3e-854e-8568-01927e927391"),
                            Article = "4",
                            Condition = 1,
                            Description = "Product 4",
                            Name = "Product 4",
                            Price = 22m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("207a6515-b7ce-835c-8569-01927e927391"),
                            Article = "5",
                            Condition = 1,
                            Description = "Product 5",
                            Name = "Product 5",
                            Price = 60m,
                            PriceWithDiscount = 11m
                        },
                        new
                        {
                            Id = new Guid("6650cd6a-f583-8719-856a-01927e927391"),
                            Article = "6",
                            Condition = 1,
                            Description = "Product 6",
                            Name = "Product 6",
                            Price = 55m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("7e8080b2-5748-8564-856b-01927e927391"),
                            Article = "7",
                            Condition = 1,
                            Description = "Product 7",
                            Name = "Product 7",
                            Price = 44m,
                            PriceWithDiscount = 14m
                        },
                        new
                        {
                            Id = new Guid("033c26e5-189e-8fda-856c-01927e927391"),
                            Article = "8",
                            Condition = 1,
                            Description = "Product 8",
                            Name = "Product 8",
                            Price = 10.99m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("33b77165-9cdb-854c-856d-01927e927391"),
                            Article = "9",
                            Condition = 1,
                            Description = "Product 9",
                            Name = "Product 9",
                            Price = 13m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("db9662e0-0db1-8138-856e-01927e927391"),
                            Article = "10",
                            Condition = 1,
                            Description = "Product 10",
                            Name = "Product 10",
                            Price = 17m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("2e0e8cbf-ff3d-819b-856f-01927e927391"),
                            Article = "11",
                            Condition = 1,
                            Description = "Product 11",
                            Name = "Product 11",
                            Price = 19m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("10f57ae3-93ee-85f3-8570-01927e927391"),
                            Article = "12",
                            Condition = 1,
                            Description = "Product 12",
                            Name = "Product 12",
                            Price = 14m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("ca05f7ef-7ade-87b8-8571-01927e927391"),
                            Article = "12",
                            Condition = 1,
                            Description = "Product 13",
                            Name = "Product 13",
                            Price = 25m,
                            PriceWithDiscount = 10m
                        });
                });

            modelBuilder.Entity("Commands.Infrastructure.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
