// <auto-generated />
using System;
using Commands.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commands.Infrastructure.Migrations
{
    [DbContext(typeof(SQLContext))]
    [Migration("20241011000519_AddInitProducts")]
    partial class AddInitProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commands.Infrastructure.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceWithDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2cd0d5a8-dbaf-813b-82be-019278e4e391"),
                            Article = "1",
                            Condition = 1,
                            Description = "Product 1",
                            ImagePath = "",
                            Name = "Product 1",
                            Price = 10.99m,
                            PriceWithDiscount = 8m
                        },
                        new
                        {
                            Id = new Guid("ec0902df-16dc-82aa-82bf-019278e4e391"),
                            Article = "2",
                            Condition = 1,
                            Description = "Product 2",
                            ImagePath = "",
                            Name = "Product 2",
                            Price = 10.99m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("419c8cf0-48b1-889a-82c0-019278e4e391"),
                            Article = "3",
                            Condition = 1,
                            Description = "Product 3",
                            ImagePath = "",
                            Name = "Product 3",
                            Price = 20m,
                            PriceWithDiscount = 11m
                        },
                        new
                        {
                            Id = new Guid("0962af2c-6324-8965-82c1-019278e4e391"),
                            Article = "4",
                            Condition = 1,
                            Description = "Product 4",
                            ImagePath = "",
                            Name = "Product 4",
                            Price = 22m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("27491939-9e44-88d5-82c2-019278e4e391"),
                            Article = "5",
                            Condition = 1,
                            Description = "Product 5",
                            ImagePath = "",
                            Name = "Product 5",
                            Price = 60m,
                            PriceWithDiscount = 11m
                        },
                        new
                        {
                            Id = new Guid("5cd9e6c8-f2f1-8c33-82c3-019278e4e391"),
                            Article = "6",
                            Condition = 1,
                            Description = "Product 6",
                            ImagePath = "",
                            Name = "Product 6",
                            Price = 55m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("1f652078-ec37-80a0-82c4-019278e4e391"),
                            Article = "7",
                            Condition = 1,
                            Description = "Product 7",
                            ImagePath = "",
                            Name = "Product 7",
                            Price = 44m,
                            PriceWithDiscount = 14m
                        },
                        new
                        {
                            Id = new Guid("9195ed82-74e3-8108-82c5-019278e4e391"),
                            Article = "8",
                            Condition = 1,
                            Description = "Product 8",
                            ImagePath = "",
                            Name = "Product 8",
                            Price = 10.99m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("d5ba80ad-3d9d-8b5b-82c6-019278e4e391"),
                            Article = "9",
                            Condition = 1,
                            Description = "Product 9",
                            ImagePath = "",
                            Name = "Product 9",
                            Price = 13m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("9ec994c5-bcda-8042-82c7-019278e4e391"),
                            Article = "10",
                            Condition = 1,
                            Description = "Product 10",
                            ImagePath = "",
                            Name = "Product 10",
                            Price = 17m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("27b7a9f3-6500-8ff9-82c8-019278e4e391"),
                            Article = "11",
                            Condition = 1,
                            Description = "Product 11",
                            ImagePath = "",
                            Name = "Product 11",
                            Price = 19m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("3b406cb7-7186-8be5-82c9-019278e4e391"),
                            Article = "12",
                            Condition = 1,
                            Description = "Product 12",
                            ImagePath = "",
                            Name = "Product 12",
                            Price = 14m,
                            PriceWithDiscount = 10m
                        },
                        new
                        {
                            Id = new Guid("28ae367f-0ef4-8d6d-82ca-019278e4e391"),
                            Article = "12",
                            Condition = 1,
                            Description = "Product 13",
                            ImagePath = "",
                            Name = "Product 13",
                            Price = 25m,
                            PriceWithDiscount = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
